name: Publish npm Package

on:
  release:
    types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.11"
      - uses: actions/cache@v5
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: bun install
      - run: bun check
      - run: bun test --concurrent --randomize
      - run: bun run build
      - run: tsc
      - run: bun pm pack
      - run: npm publish
